### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by serut** [privatenumber/instant-mocha#6]
Hello,

I struggle to use your fork with Webpack 5:

```
node:14344) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
Error: Module.id: There was no ChunkGraph assigned to the Module for backward-compat (Use the new API)
    at /home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/webpack/lib/ChunkGraph.js:1548:12
    at deprecated (internal/util.js:89:15)
    at Function.getChunkGraphForModule (/home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/webpack/lib/ChunkGraph.js:1539:18)
    at CompatGetDefaultExportRuntimeModule.get id [as id] (/home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/webpack/lib/Module.js:172:21)
    at /home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/mochapack/src/webpack/util/getAffectedModuleIds.ts:43:51
    at Array.reduce (<anonymous>)
    at Set.set.<computed> [as reduce] (/home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/webpack/lib/util/deprecation.js:87:35)
    at buildModuleMap (/home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/mochapack/src/webpack/util/getAffectedModuleIds.ts:42:29)
    at Object.getAffectedModuleIds [as default] (/home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/mochapack/src/webpack/util/getAffectedModuleIds.ts:144:32)
    at Object.getBuildStats [as default] (/home/leo/CS/rs-dev/regards-oss-frontend/webapp/plugins/criterion/data-with-picture-only/node_modules/mochapack/src/webpack/util/getBuildStats.ts:20:47)
```

did you test with a real project ?

**Comment by serut** [comment]
You can reproduce using :

```
git clone https://github.com/serut/regards-frontend-webpack-5
cd webapp
npm i
npm run test:mocha
```

Webpack config is inside `/webapp/webpack-config-front/src/app/webpack.test.config.js`

**Comment by privatenumber** [comment]
Yep, tested and working with a large enterprise project.

Thanks for the repro. I'm getting a different error than you. Can you provide your `instant-mocha` command?

FYI, this isn't a fork

**Comment by privatenumber** [comment]
Also seems like you [upgraded to Webpack 5](https://github.com/serut/regards-frontend-webpack-5/commit/d55de663870281bc2d0e99b0965b014a3202e537#diff-006cce2fd88392a0bff4cf16091d480b6238c6bdf52c9042bf7805879c791a8f) without confirming that `instant-mocha` is working.

`instant-mocha` supports both Webpack 4 & 5. Please test in isolation with Webpack 4 if that was already working for you.

And if possible, please provide a minimal reproduction of the error.

**Comment by serut** [comment]
With or without webpack 5 I have the same error (after fixing test cmd) : 
```
Cannot find module 'chai'
Require stack:
- /main.js
- /home/leo/CS/rs-dev/regards-oss-frontend/webapp/node_modules/instant-mocha/dist/lib/memfs.js
- /home/leo/CS/rs-dev/regards-oss-frontend/webapp/node_modules/instant-mocha/dist/lib/mocha.js
- /home/leo/CS/rs-dev/regards-oss-frontend/webapp/node_modules/instant-mocha/dist/instant-mocha.js
- /home/leo/CS/rs-dev/regards-oss-frontend/webapp/node_modules/instant-mocha/dist/cli.js
- /home/leo/CS/rs-dev/regards-oss-frontend/webapp/node_modules/instant-mocha/bin/instant-mocha.js
npm ERR! code ELIFECYCLE
```

Sorry I thought it was a fork..

**Comment by serut** [comment]
If I had `/chai/,` to the whitelist inside `externals: [nodeExternals` it founds chai, but then it's another dependency that's missing...

**Comment by serut** [comment]
I removed `externals` and `module.noParse` from my webpack test conf to make it compiles. Now some mocks are not working anymore, but it looks like a lot of things are working as expected.
Congratz !

**Comment by serut** [comment]
Now I've fixed my stub, the runner does not stop when finished.

The command just hangs with : 

```
  3082 passing (3s)

[mochawesome] Report JSON saved to /home/leo/CS/rs-dev/regards-oss-frontend/webapp/reports/mocha/mochawesome.json

[mochawesome] Report HTML saved to /home/leo/CS/rs-dev/regards-oss-frontend/webapp/reports/mocha/mochawesome.html


```
